### ISSUE TITLE
memory allocation failed.

### ISSUE THREAD

**Issue by water5** [adafruit/Adafruit_CircuitPython_RSA#15]
Which series chip tested ?
I receive below when I import adafruit_rsa on STM32F405RGT6:
`import adafruit_rsa`

> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> File "/lib/adafruit_rsa/__init__.py", line 27, in <module>
> File "/lib/adafruit_rsa/pkcs1.py", line 31, in <module>
> File "/lib/adafruit_hashlib/__init__.py", line 45, in <module>
>MemoryError: memory allocation failed, allocating 2933 bytes

**Comment by jerryneedell** [comment]
Try using the "precompiled" .mpy version of the libraries - https://circuitpython.org/libraries -- I had the same error, but used the .mpy version for the adafruit_haslib and it was able to load.
Probably best to use the .mpy version fo all.  They need much less RAM to load.

**Comment by water5** [comment]
Thanks, it works fine.
