### ISSUE TITLE
pyasn1 not implement currently?

### ISSUE THREAD

**Issue by water5** [adafruit/Adafruit_CircuitPython_RSA#16]
I want to test load/save pem, der format key, but the pyasn1 module looks like not work currently,

`from pyasn1.type import univ, namedtype, tag`

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "univ.py", line 10, in <module>
>   File "error.py", line 37, in <module>
> TypeError: multiple bases have instance lay-out conflict

**Comment by evaherrada** [comment]
I may take a look at this

**Comment by brentru** [comment]
@dherrada  fwiw, glancing at the issue, i feel the latest pyasn1 might've changed the function signatures

**Comment by brentru** [comment]
@dherrada  Do you still want to take a look at this?

**Comment by evaherrada** [comment]
@brentru _yes_, but I don't think I'll have enough time to look at it. I'll unassign myself

**Comment by evaherrada** [comment]
@brentru I've got a bit of time today, so I'll take a look at it

**Comment by brentru** [comment]
Nice! I'll take this on sometime next week if you can't crack it or don't have time to :)

**Comment by brentru** [comment]
@water5  We do not currently support the pyasn1 module in this library (too memory intense for SAMD51 in its current implementation), and loading PEM Files not supported by this CircuitPython library.

see: https://github.com/adafruit/Adafruit_CircuitPython_RSA/blob/master/adafruit_rsa/key.py#L113
