### ISSUE TITLE
Update RTD parameter documentation

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_RSA#23]
This library is missing Sphinx docstring documentation for ReadTheDocs for the functions contained within!  See other libraries for examples.  Here's a basic example of what is needed in the docstring for each function:

```python
...

def some_function(a: float, b: int) -> Tuple[str, str, str]:
    """This is an explanation of the function

    :param float a: An explanation of parameter a
    :param int b: An explanation of parameter b
    """

...
```

**Comment by jposada202020** [comment]
Closed by #27 . Verified in RTD. 

Thanks @elpekenin for the heads up :) !
