### ISSUE TITLE
Why are range and zip assigned to themselves

### ISSUE THREAD

**Issue by evaherrada** [adafruit/Adafruit_CircuitPython_RSA#8]
Does anyone know why this is done? Pylint 2.x doesn't like it and although it appears like there were disables put in to ignore the issues caused by this, I wanted to check before adding another disable.

https://github.com/adafruit/Adafruit_CircuitPython_RSA/blob/39330c687e7bf9220d277838951b827bb822c540/adafruit_rsa/_compat.py#L43-L45

Referencing main issue: adafruit/Adafruit_CircuitPython_Bundle#232

**Comment by evaherrada** [comment]
@kattni

**Comment by evaherrada** [comment]
Also, these are all non top-level imports that pylint 2.x doesn't like. This wasn't changed by black and pylint 1.9.2 is fine with it. I assume this is to save on resources.
https://github.com/adafruit/Adafruit_CircuitPython_RSA/blob/39330c687e7bf9220d277838951b827bb822c540/adafruit_rsa/key.py#L259-L260
https://github.com/adafruit/Adafruit_CircuitPython_RSA/blob/39330c687e7bf9220d277838951b827bb822c540/adafruit_rsa/key.py#L272-L273
https://github.com/adafruit/Adafruit_CircuitPython_RSA/blob/39330c687e7bf9220d277838951b827bb822c540/adafruit_rsa/key.py#L337-L339
https://github.com/adafruit/Adafruit_CircuitPython_RSA/blob/39330c687e7bf9220d277838951b827bb822c540/adafruit_rsa/key.py#L477
https://github.com/adafruit/Adafruit_CircuitPython_RSA/blob/39330c687e7bf9220d277838951b827bb822c540/adafruit_rsa/key.py#L516-L517

**Comment by evaherrada** [comment]
Personally, I think that we should either move these to top-level imports or just add a disable in each method that has such an import

**Comment by brentru** [comment]
@dherrada  Let's try moving them to top-level imports.

**Comment by brentru** [comment]
@dherrada  this may have been for Python2 compatibility within the python-rsa library which this is based on.

It's since been removed from their `master` branch's `_compat.py`:
https://github.com/sybrenstuvel/python-rsa/commit/ded036cf988b0cf4b20002d88434282f30762638#diff-331cbe2ce57debdeab49e0d23b70d312L43

They can be removed, but will need to test prior to merging in to make sure it doesn't affect anything. Feel free to assign me to this.

**Comment by brentru** [comment]
This has been updated in https://github.com/adafruit/Adafruit_CircuitPython_RSA/pull/10 and merged into `master`. De-assigning then closing.
